### ISSUE TITLE
fatal error: can't find local.zeek

### ISSUE THREAD

**Issue by shadonet** [zeek/zeekctl#35] opened 2021-07-17 06:53 UTC
After a fresh install of Zeek on FreeBSD system, I got this error when I ran this command:

`zeekctl deploy
`

> checking configurations ...
> zeek scripts failed.
> fatal error: can't find local.zeek

Zeek: 4.0.2
FreeBSD: 12.2
ZeekControl: 2.3.0

Apparently this file is not present under /usr/local/share/zeek/site (the local.zeek.sample file is present).

**Comment by 0xxon** [comment] 2021-07-19 08:24
Is this with a source installation, or with an installation from the FreeBSD ports tree?

**Comment by shadonet** [comment] 2021-07-19 08:59
Installation from the FreeBSD ports tree

**Comment by 0xxon** [comment] 2021-07-19 09:25
In that case - I assume that this is not a bug, but a decision of the FreeBSD port maintainers.

@leres might be able to shed some light on this.

**Comment by leres** [comment] 2021-07-19 17:16
> In that case - I assume that this is not a bug, but a decision of the FreeBSD port maintainers.

As the maintainer of  security/zeek, I'd say it was definitely a bug in the port. Now fixed via [7c9b2f40c5f2](https://cgit.freebsd.org/ports/commit/?id=7c9b2f40c5f2557d87cc1d2ce7d968377b13d6b3).

**Comment by 0xxon** [comment] 2021-07-20 06:04
Thank you :)

**Closed by 0xxon** 2021-07-20 06:04 UTC
